name: Auto Update IPTV List

on:
  schedule:
    # গিটহাবের ভিড় এড়াতে প্রতি ঘণ্টার ১৭ এবং ৪৭ নম্বর মিনিটে রান হবে (৩০ মিনিট ব্যবধান)
    - cron: '17,47 * * * *'
  workflow_dispatch:        # গিটহাব থেকে ম্যানুয়ালি রান করার জন্য

# গিটহাবে চেঞ্জ পুশ করার রাইট পারমিশন
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run script
      env:
        # গিটহাব সিক্রেট থেকে কাস্টম সোর্স ডাটা পাইথন কোডে পাঠানো হচ্ছে
        MY_CUSTOM_SOURCES: ${{ secrets.MY_CUSTOM_SOURCES }}
      run: python main.py

    - name: Commit and push updated playlist and json
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add playlist.m3u channels.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto update playlist and json" && git push)
