name: Auto Update IPTV Playlist

on:
  schedule:
    # গিটহাবের নিয়ম অনুযায়ী প্রতি ১ ঘণ্টা পর পর শিডিউল রাখা হলো (গিটহাব ঠিক ৩০ মিনিট এলাউ করে না)
    - cron: '0 * * * *'
  workflow_dispatch: # ম্যানুয়ালি বা এক্সটার্নাল রিকোয়েস্ট দিয়ে রান করার জন্য

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Python Script
        env:
          # আপনার গিটহাব সিক্রেট থেকে সোর্স লোড করবে
          MY_CUSTOM_SOURCES: ${{ secrets.MY_CUSTOM_SOURCES }}
        run: |
          python main.py

      - name: Commit and Push Updated Files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add playlist.m3u channels.json
          git status
          git commit -m "Auto update playlist and channels.json" || exit 0
          git push
