name: Auto Update Xtream Playlist

on:
  schedule:
    - cron: '0 * * * *'   # Every 1 hour
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Generate Playlist
      run: python xtream_playlist.py

    - name: Commit and push updates
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        touch playlist_x.m3u
        git add playlist_x.m3u
        git commit -m "🔁 Auto update Playlist X $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git pull --rebase
        git push
